        const fr = {
        titre:"spawn! - Le festival du jeu vidéo d'Angoulême",
        titremention:"Mentions légales",
        apropos : "À PROPOS",
        billeterie : "BILLETTERIE",
        programme : "PROGRAMME",
        demijournée : "DEMI-JOURNÉE PRO",
        partenaires : "PARTENAIRES",
        infospratiques : "INFOS PRATIQUES",
        edition2024: "ÉDITION 2024",
        festivalangouleme : "Le festival du jeu vidéo d’Angoulême",
        edition3 : "revient pour une troisième édition",
        evenement : "Cet événement est organisé par le Cnam-Enjmin, la grande école publique du jeu vidéo et du numérique, SO· Games, l'association des professionnelles et professionnels du jeu vidéo en Nouvelle-Aquitaine et le Pôle Image Magelis, écosystème dédié au développement de la filière image en Charente. <br/> spawn! c’est LE rendez-vous ludique incontournable de l’année à Angoulême.",
        quand : "QUAND ?",
        date : "Samedi 5 avril 2025 <br/> de 10h à 20h",
        ou : "OÙ ?",
        batiment: "Cnam-Enjmin (bâtiment le Nil) <br/> 138 rue de Bordeaux <br/> 16000 Angoulême",
        jeux: "Près de <b> 100 jeux à tester :</b> <br/> jeux indés, originaux, expériences inédites, réalité virtuelle...",
        culture: "<b> 4 tables rondes et conférences </b> sur la culture vidéoludique",
        spectacles: "Spectacles vidéoludiques",
        studios:"<b>Rencontres</b> avec des <b>studios indépendants</b> de jeux vidéo",
        challenges:"<b>Challenges : </b>Super Smash Bros, Mario Kart, Rocket League et Just Dance",
        demijourneepro: "Une demi-journée réservée au professionnelles et professionnels du jeu vidéo aura lieu le <b>vendredi 4 avril 2025</b>.",
        evenementfamilial:"Événement familial, gratuit, ouvert à toutes et tous sur inscription Eventbrite dans la limite des places disponibles.",
        inscription:"<a href='https://www.eventbrite.com/e/billets-spawn-le-festival-du-jeu-video-dangouleme-1223204249839'> S’inscrire gratuitement</a>",   
        lastedition:"RETOUR SUR L'ÉDITION PRÉCÉDENTE",
        h1018:"De 10h à 18h :",
        testjeux:"Près de 100 jeux à tester : jeux indés, originaux, expériences inédites, réalité virtuelle... ",
        meetstudio:"Rencontres avec des studios indépendants de jeux vidéo",
        et:"et",
        capbd:"Cap BD expose 6 artistes : Beloup, Chario Spirale, Fanny MAREC, Garance ROYÈRE, Mecchi et Geoffroy Monde",
        expo:"Expo 'Elles font le jeu vidéo' : panorama de 9 créatrices d’Ada LOVELACE à Julie LE BARON",
        aajh:"Stand Association Angoumoisine de Jeux et d'Histoire (AAJH) : jeux avec figurines et jeux de rôle",
        capgamearena:"CapGame Arena : une compétition accessible à toutes et à tous autour de 3 jeux (Street Fighter 6, Forza Motorsport et Efootball) organisée par CapGame, une association qui agit pour améliorer l’inclusion des personnes en situation de handicap à la vie numérique",
        h1120:"De 11h à 20h : ",
        amphitheatre:"Programmation en amphithéâtre, animée par <a href='https://bsky.app/profile/dollywood.sbsky.social'> DollyWood </a>,<span class='bold'> créatrice de contenus </span> et Camille ALEXANDRE (<a href='https://bsky.app/profile/quineapple.bsky.social'>Quineapple</a>), <span class='bold'> co-rédactrice en chef et présentatrice de Jour de Play pour ARTE.",
        YouTube:"La programmation de 11h à 18h30 sera diffusée en live et en replay sur la <a href='https://www.youtube.com/channel/UCIivvuWawHcNcgxdAdRm87w'> chaîne YouTube du Cnam-Enjmin </a> et interprétée en langue des signes française (LSF) grâce au soutien financier du <a href='https://www.sell.fr/'> SELL, le Syndicat des Éditeurs de Logiciels de Loisirs.</a>",
        h111145:"11h00 <br>–<br> 11h45",
        sujet1:"PEGI, ESRB, pourquoi mettre un âge?",
        sujet1intervenants: "Catherine <span style='text-transform: uppercase; color:var(--c-black);'> Rolland </span> <br> Rémy <span style='text-transform: uppercase; color:var(--c-black);'> Devaux </span> <br> Mickaël <span style='text-transform: uppercase; color:var(--c-black);'> Newton </span>",
        tableronde:"Table ronde",
        h121245:"12h00 <br>-<br> 12h45",
        sujet2:"Jeux vidéo, cinéma, littérature : quand les médias s'adaptent",
        sujet2intervenants:"<span style='text-transform: uppercase; color:var(--c-black);'> Luma </span><br>David <span style='text-transform: uppercase; color:var(--c-black);'> Duriot </span><br>Alexis <span style='text-transform: uppercase; color:var(--c-black);'> Blanchet </span>",
        h1314:"13h00 <br>-<br> 14h00",
        sujet3:"Battle de dessin sur le thème du jeu vidéo",
        sujet3intervenants:"David <span style='text-transform: uppercase; color:var(--c-black);'> Duriot </span> - Animateur <br> 4 auteurs · autrices de BD : <br> Chario Spirale <br> Beloup <br> Mecchi <br> Geoffroy Monde",
        h141445:"14h00 <br>-<br> 14h45",
        sujet4:"Retour des salles d'arcade grâce à la réalité virtuelle (VR)",
        sujet4intervenants:"Pierre-Edouard <span style='text-transform: uppercase; color:var(--c-black);'> Nobels </span> <br> Pa Ming <span style='text-transform: uppercase; color:var(--c-black);'> Chiu </span>",
        h151545:"15h00 <br>-<br> 15h45",
        sujet5:"Les zombies dans le jeu vidéo",
        sujet5intervenants:"David <span style='text-transform: uppercase; color:var(--c-black);'> Elahee </span> <br> Mélissandre <span style='text-transform: uppercase; color:var(--c-black);'> Monatus </span> <br> Christophe <span style='text-transform: uppercase; color:var(--c-black);'> Butelet </span>",
        h161645:"16h00 <br>-<br> 16h45",
        h171830:"17h00 <br>-<br> 18h30",
        sujet7:"Point'n Think (enregistrement en direct)",
        sujet7intervenants:'Julien <span style="text-transform: uppercase; color:var(--c-black);"> Djoubri </span> <br> Axel <span style="text-transform: uppercase; color:var(--c-black);"> Billoudet </span> <br> Jüles <span style="text-transform: uppercase; color:var(--c-black);"> Delétoile </span> <br> 3 invitées · invités : <br> Géraud <span style="text-transform: uppercase; color:var(--c-black);"> Zucchini </span> <br> Sekamelica <br> Julien <span style="text-transform: uppercase; color:var(--c-black);"> Éveillé </span>',
        h1920:"19h00 <br>-<br> 20h00",
        demijournée2:"DEMI-JOURNÉE RÉSERVÉE AUX PROS",
        spawnpro:"<span class='spawncolor upper'>spawn!</span><span class='upper'> pro </span> est un cycle de conférences et de rencontres entre professionnelles et professionnels de l’industrie qui aura lieu le vendredi 4 avril 2025 à partir de 14h. <br /><br> Le but de cette manifestation est de diffuser les bonnes pratiques indies qui permettent de se professionnaliser.",
        auprogramme:"Au programme:",
        spawnprogramme:"<li>Cycle de conférences de 14h à 18h10 (accessible aux étudiantes · étudiants)</li> <li>Afterwork SO· Games de 18h30 à 21h30 (réservé aux pro)</li><li><a href='https://docs.google.com/forms/d/e/1FAIpQLSeWB2leFRESKQR_53jr-AemeR-6LwVZFkafYEmp8-vOUknsEw/viewform'>Sur inscription</a></li>",
        h141410:"14h00 <br>-<br> 14h10",
        sujet9:"Lancement",
        h14101420: "14h10 <br>-<br> 14h20",
        sujet10:"Faciliter l'accès aux jeux vidéo pour les publics en situation de handicap",
        video:"Vidéo",
        h142015:"14h20 <br>-<br> 15h00",
        sujet11:"Développer des jeux engagés",
        sujet11intervenants:"Farhanaz 'Joy' <span style='text-transform: uppercase; color:var(--c-black);'> Elahee </span> (animatrice) <br> Pierre <span style='text-transform: uppercase; color:var(--c-black);'> Corbinais </span> <br> Émi <span style='text-transform: uppercase; color:var(--c-black);'> Lefèvre </span>",
        h15051545:"15h05 <br>-<br> 15h45",
        sujet12:"Contrer les vagues : les communautés de jeux construisent l’inclusivité",
        sujet12intervenants:"Jennifer <span style='text-transform: uppercase; color:var(--c-black);'> Lufau </span> <br> Vanessa <span style='text-transform: uppercase; color:var(--c-black);'> Chicout </span>",
        conférence:"Conférence",
        h15501630:"15h50 <br>-<br> 16h30",
        sujet13:"De Bomb Club à Fakutori ou comment développer un hobby ?",
        sujet13intervenants:"Antoine <span style='text-transform: uppercase; color:var(--c-black);'> Latour </span>",
        h16351715:"16h35 <br>-<br> 17h15",
        sujet14:"Méta-jeu & Puzzle Games : Construction d'une épiphanie",
        h172018:"17h20 <br>-<br> 18h00",
        sujet15:"'Pas de politique dans mon jeu vidéo'... ou pas",
        heure16:"18h00 <br>-<br> 18h10",
        sujet16:"Mot de la fin",
        organisateurs:"ORGANISATEURS",
        remerciement:"Merci à tous nos partenaires de leur confiance",
        venue:"PRÉPARER VOTRE VENUE",
        voiture:"EN VOITURE",
        itinérairevoiture:"<span class='text-wrapper' >Vous pouvez vous garer <br /> sur le parking gratuit du Musée de la BD <br />et emprunter ensuite la passerelle<br /></span><a href='https://enjmin.cnam.fr/medias/fichier/plancampus-enjmin_1500992127194-pdf?ID_FICHE=1327678&INLINE=FALSE' target='_blank' rel='noopener noreferrer'><span class='text-wrapper-2'>( téléchargez le plan d'accès )</span></a>)",
        bus:"EN BUS",
        itinérairebus:"<span class='text-wrapper' >Descendez à l'arrêt de bus 'Le Nil' <br />desservi par les lignes 5 et 3<br /> ou 'La Cité' desservi par les lignes 6 et 9</span><a href='https://www.stga.fr/'><span class='text-wrapper-2'>( plus d'information )</span></a>)",
        reseauxsociaux:"Réseaux sociaux",
        contact:"<a class='redirectToPage' href='./contacts.html'>Contact et équipe</a>",
        organisateursmin:"Organisateurs",
        info:"© Cnam-Enjmin | <a class='redirectToPage' href='./mentions.html'>Mentions légales</a> | <a class='redirectToPage' href='https://enjmin.cnam.fr/enjmin/programme-spawn-2025-1535161.kjsp?RH=1499863421832'> Programme spawn! 2025 </a> | <a class='redirectToPage' href='https://enjmin.cnam.fr/enjmin/cp-spawn-2025--1535160.kjsp?RH=1499863421832'>  Communiqué de presse spawn! 2025 </a>",
        jgp:"Journée grand public",
        com:"<span class='text-wrapper'>Coordination générale, communication &amp; presse<br /></span><span class='smallerText'>Stéphanie BOCQUILLON BREL : stephanie.bocquillon-brel@lecnam.net<br /></span><span class='text-wrapper'><br />Partenariats<br /></span><span class='smallerText'>Indira VALDIVIA-VIZARRETA : indira.valdivia@lecnam.net</span>",
        djp:"Demi-journée Pro",
        coordination:"<span class='text-wrapper'>Coordination générale<br /></span><span class='smallerText'>David ELAHEE : david.elahee@gmail.com<br />Marie-Charlotte YNESTA : marie-charlotte@sogames.org<br /><br /></span><span class='text-wrapper'>Communication<br /></span><span class='smallerText'>Capucine CHAUFFOURIER : capucine@sogames.org</span>",
        teams:"EQUIPES",
        enjminteam:"<span class='text-wrapper'>Stéphanie BOCQUILLON BREL,</span><span class='smallerText'> responsable communication<br /><br /></span><span class='text-wrapper'>Axel BUENDIA,</span><span class='smallerText'> directeur<br /><br /></span><span class='text-wrapper'>Eric DEBENAT,</span><span class='smallerText'> technicien informatique<br /><br /></span><span class='text-wrapper'>Bérénice FOUCHARD,</span><span class='smallerText'> graphiste<br /><br /></span><span class='text-wrapper'>May HUBERT,</span><span class='smallerText'> assistante de formation et chargée d’événementiel<br /><br /></span><span class='text-wrapper'>Thomas MAYOUX et Florian BONNIN,</span><span class='smallerText'> développeurs<br /><br /></span><span class='text-wrapper'>Linda MIKHAIL,</span><span class='smallerText'> chargée de communication<br /><br /></span><span class='text-wrapper'>Indira VALDIVIA-VIZARRETA,</span><span class='smallerText'> responsable des partenariats et des relations internationales<br /><br /></span><span class='text-wrapper'>Margaux VIRIEU,</span><span class='smallerText'> secrétaire générale</span>",
        sogamesteam:"<span class='text-wrapper'>Capucine CHAUFFOURIER,</span><span class='smallerText'> chargée de communication<br /><br /></span><span class='text-wrapper'>Camille COQ,</span><span class='smallerText'> curatrice de la sélection<br /><br /></span><span class='text-wrapper'>William DAVID,</span><span class='smallerText'> curateur puzzle<br /><br /></span><span class='text-wrapper'>David ELAHEE,</span><span class='smallerText'> président, web designer, curation, programmation, suivi, cofondateur du FJA<br /><br /></span><span class='text-wrapper'>Farhanaz ELAHEE,</span><span class='smallerText'> coordinatrice Cap BD<br /><br /></span><span class='text-wrapper'>Sébastien FONTAINE,</span><span class='smallerText'> logistique, cofondateur du FJA<br /><br /></span><span class='text-wrapper'>Robinson LACOTTE,</span><span class='smallerText'> curateur des expériences<br /><br /></span><span class='text-wrapper'>Mylène LOURDEL,</span><span class='smallerText'> vice-présidente événement, programmation, curation des conférences grand public<br /><br /></span><span class='text-wrapper'>Marie-Charlotte YNESTA,</span><span class='smallerText'> déléguée générale</span>",
        guests:"Nos super guests et membres de comités !",
        membres:"<span class='text-wrapper'>Adrien LAROUZÉE,</span><span class='smallerText'> responsable du pilotage des projets numériques - ARTE <br /></span><span class='text-wrapper'><br />⁠Céline HIRTZ-GARDRÉ,</span><span class='smallerText'> chargée de projets numériques - Médiathèque L'Alpha<br /></span><span class='text-wrapper'><br />Tanguy TAILLANDIER,</span><span class='smallerText'> conseiller et animateur numérique - CSCS / MJC Rives de Charente <br /></span>",
        membres2:"<span class='text-wrapper'>Dolly Wood,</span><span class='smallerText'> créatrice de contenus<br /></span><span class='text-wrapper'><br />Quineapple,</span><span class='smallerText'> co-rédactrice en chef et présentatrice de <i> Jour de Play </i> - ARTE<br /><br /></span><span class='text-wrapper'>David BEAUVALLET,</span><span class='smallerText'> directeur marketing et communication - Magelis<br /></span>",
        mentionslegales:"MENTIONS LÉGALES",
        enjminsiret:"<span class='titleGroup'>Cnam-Enjmin<br /><br /></span><span class='text-wrapper-12'>Siret : 197 534 712 00017 - Forme juridique : Établissement public national à caractère scientifique culturel et professionnel - Code activité : </span><br /><span class='text-wrapper-12'>Enseignement supérieur (85.42Z) - TVA intracommunautaire : FR11197534712 - Adresse : 138 rue de Bordeaux 16000 Angoulême<br /><br /><br /></span><span class='text-wrapper-12'>Directeur : Axel BUENDIA<br /><br /><br /></span><span class='titleGroup'>SO· Games<br /><br /></span><span class='text-wrapper-12'>Siret : 50539681200024 – Forme juridique : Association loi 1901 – Code activité : Autres organisations fonctionnant par adhésion volontaire (9499Z)<br /></span> <span class='text-wrapper-12'> TVA intracommunautaire : FR35505396812 – Adresse : 12 place de la Bourse 33000 Bordeaux<br /><br /><br /></span> <span class='text-wrapper-12'>Président : David ELAHEE<br /></span>",    
        hebergement:"Hébergement : Cnam-Enjmin Tous droits réservés 2017-2025 – Cnam-Enjmin et SO· Games",
        fr:"Français",
        en:"Anglais",
    };
    const en = {
        titre:"spawn! - Angoulême’s Video Game Festival",
        titremention:"Legal notice",
        apropos : "ABOUT SPAWN!",
        billeterie : "TICKETS",
        programme : "PROGRAMME",
        demijournée : "PRO HALF-DAY",
        partenaires : "PARTNERS",
        infospratiques : "PRACTICAL INFO",
        edition2024: "2024 EDITION",
        festivalangouleme : "Angoulême’s Video Game Festival ",
        edition3 : "is back for its third edition ",
        evenement: "The event is co-organised by Cnam-Enjmin, the leading French National School for Video Games and Digital Interactive Media, SO· Games, the association for video game professionals in the Nouvelle-Aquitaine Region, and Pôle Image Magelis, an educational ecosystem dedicated to the development of the visual image sector in the Charente Department. <br/> spawn! is THE unmissable fun event of the year in Angoulême. ",        
        quand : "WHEN?",
        date : "Saturday 5th April 2025 10am – 8pm ",
        ou : "WHERE?",
        batiment: "Cnam-Enjmin (Nil Building) <br/> 138 rue de Bordeaux <br/> 16000 Angoulême, France", 
        jeux: "Nearly <b> 100 games to try out:</b> <br/> Independent, original and unreleased games, virtual reality and much more! ",
        culture:"<b> 4 round-table discussions and conferences </b> about video game culture ",
        spectacles:"Video Game Performances",
        studios: "<b>Meet independent</b> video game studios ",
        challenges:"<b>Challenges: </b> Super Smash Bros, Mario Kart, Rocket League and Just Dance",
        demijournéepro:"<b>On 4th April 2025</b>, there is a half-day event reserved just for video game professionals. ",
        evenementfamilial:"spawn! is a family event, open to everybody of all ages. Register on Eventbrite. ",
        inscription:"<a href='https://www.eventbrite.com/e/billets-spawn-le-festival-du-jeu-video-dangouleme-1223204249839'> S’inscrire gratuitement</a>",
        lastedition:"RELIVE LAST YEAR'S EVENT",
        h1018:"10am – 6pm ",
        testjeux:"Nearly 100 games to test out: Independent, original and unreleased games, virtual reality and much more! ",
        meetstudio:"Meet independent video game studios ",
        et:"and",
        capbd:"CAP BD (an association in Angoulême which promotes the art of comic books) exhibits 6 artists: Beloup, Chario Spirale, Fanny Marec, Garance Royère, Mecchi and Geoffroy Monde ",        
        expo:"<i font-style:italic>'Elles font le jeu vidéo'</i> ('They make video games') Exhibit: Overview of 9 female creators, including Ada Lovelace and Julie Le Baron ",
        aajh:"Angoulême Association of Video Games and History (AAJH) Stand: Games with figurines and role play games ",
        capgamearena:"CapGame Arena: Game Competition accessible to everyone with 3 games (Street Fighter 6, Forza Motorsport and Efootball) organised by CapGame, an association which improves disabled people’s access and inclusion in digital life ",
        h1120:"11am to 8pm ",
        amphitheatre:"Programme of round-table discussions and conferences in the lecture theatre. Hosted by <a href='https://bsky.app/profile/dollywood.sbsky.social'> DollyWood</a>,<span class='bold'> CONTENT CREATOR</span>, and Camille Alexandre (<a href='https://bsky.app/profile/quineapple.bsky.social'>Quineapple</a>), <span class='bold'> CO-EDITOR AND HOST of <i>Jour de Play</i> for the Franco-German TV channel, ARTE. </span>  ",
        YouTube:"The entire programme will be broadcast live and then available on catch-up on <a href='https://www.youtube.com/channel/UCIivvuWawHcNcgxdAdRm87w'> Cnam-Enjmin’s YouTube channel</a> and will be interpreted in French Sign Language thanks to the financial support of <a href='https://www.sell.fr/'> SELL</a>, the French Union of Publishers of Leisure Software (<i>Syndicat des éditeurs de logiciels de loisirs</i>) ",
        h111145:"11am <br>–<br> 11:45am ",
        sujet1:"PEGI, ESRB: Why put an age? ",
        sujet1intervenants:"Catherine Rolland <br> Rémy Devaux <br> Mickaël Newton <br>",
        tableronde: "Round-table discussion ",
        h121245:"12pm <br>-<br> 12:45pm",
        sujet2:"Video Games, Cinema, Literature: When medias adapt",
        sujet2intervenants:"Luma <br> David Duriot <br> Alexis Blanchet",
        h1314:"1pm <br>-<br> 2pm",
        sujet3:"Drawing Battle centred around the theme of Video Games ",
        sujet3intervenants:"David Duriot - Host <br> 4 Comic Book Authors: <br> Chario Spirale <br> Beloup <br> Mecchi <br> Geoffroy Monde",
        h141445:"2pm <br>-<br> 2:45pm",
        sujet4:"Reliving Arcade Games thanks to Virtual Reality",
        sujet4intervenants:"Pierre-Edouard Nobels <br> Pa Ming Chiu",
        h151545:"3pm <br>-<br> 3:45pm",
        sujet5:"Zombies in Video Games ",
        sujet5intervenants:"David Elahee <br> Mélissandre Monatus <br> Christophe Butelet",
        h161645:"4pm <br>-<br> 4:45pm",
        h171830:"5pm <br>-<br> 6:30pm",
        sujet7:"Point'n Think (Live Recording)",
        sujet7intervenants:'Julien Djoubri <br> Axel Billoudet <br> Jüles Delétoile <br> 3 Guests: <br> Géraud Zucchini <br> Sekamelica <br> Julien Éveillé </span>',
        h1920:"7pm <br>-<br> 8pm",
        demijournée2:"HALF-DAY RESERVED FOR VIDEO GAME PROFESSIONALS",
        spawnpro:"<span class='spawncolor upper'>spawn!</span><span class='upper'> pro </span>is a line-up of conferences and meetings between industry professionals. It will take place on Friday 4th April 2025 from 2pm onwards.<br/><br> The event’s goal is to spread good practices from independent studios to help individuals become more professional.",
        auprogramme:"Programme:",
        spawnprogramme:"<li>Conferences cycle from 2pm to 6:10pm (accessible to students)</li> <li>SO· Games Afterwork drinks from 6:30pm to 9:30pm (professionals only)</li><li><a href='https://docs.google.com/forms/d/e/1FAIpQLSeWB2leFRESKQR_53jr-AemeR-6LwVZFkafYEmp8-vOUknsEw/viewform'>On registration (link only available in French)</a></li>",
        h141410:"2pm <br>-<br> 2:10pm",
        sujet9:"Launch",
        h14101420: "2:10pm <br>-<br> 2:20pm",
        sujet10:"Facilitating Disabled People’s Access to Video Games",
        video:"Video",
        h142015:"2:20pm <br>-<br> 3pm",
        sujet11:"Developing Engaging Games",
        sujet11intervenants:"Farhanaz 'Joy' Elahee (Host) <br> Pierre Corbinais <br> Émi Lefèvre",
        h15051545:"3:05pm <br>-<br> 3:45pm",
        sujet12:"Countering Waves: Gaming Communities build Inclusivity",
        sujet12intervenants:"Jennifer Lufau <br> Vanessa Chicout",
        conférence:"Conference",
        h15501630:"3:50pm <br>-<br> 4:30pm",
        sujet13:"From Bomb Club to Fakutori: How to develop a hobby? ",
        sujet13intervenants:"Antoine Latour",
        h16351715:"4:35pm <br>-<br> 5:15pm",
        sujet14:"Meta-game & Puzzle Games: Building an Epiphany",
        h172018:"5:20pm <br>-<br> 6pm",
        sujet15:"“No politics in my video game”, or is there… ",
        heure16:"6pm <br>-<br> 6:10pm",
        sujet16:"Closing words",
        organisateurs:"ORGANISERS",
        remerciement:"A big thank you to our partners for their confidence",
        venue:"PREPARE YOUR VISIT",
        voiture:"BY CAR",
        itinérairevoiture:"<span class='text-wrapper' >You can park <br /> in the free car park at the Comic Book Museum (Musée de la BD) <br />and take the footbridge across the river<br /></span><a href='https://enjmin.cnam.fr/medias/fichier/plancampus-enjmin_1500992127194-pdf?ID_FICHE=1327678&INLINE=FALSE' target='_blank' rel='noopener noreferrer'><span class='text-wrapper-2'> Download the access map </span></a>)",
        bus:"BY BUS",
        itinérairebus:"<span class='text-wrapper' >Take lines 3, 5, 60 or 71 <br />and get off at 'Le Nil', <br />or take lines 6 or 9 and get off at 'La Cité' </span><a href='https://www.stga.fr/'><span class='text-wrapper-2'> More info on the STGA transport Website</span></a>)",
        reseauxsociaux:"Social Media",
        contact:"<a class='redirectToPage' href='./contacts.html'>Contacts and Team</a> ",
        organisateursmin:"Organisers",
        info:"© Cnam-Enjmin | <a class='redirectToPage' href='./mentions.html'>Legal Notice</a> | <a class='redirectToPage' href='https://enjmin.cnam.fr/enjmin/programme-spawn-2025-1535161.kjsp?RH=1499863421832'>spawn! 2025 programme (in French)</a> | <a class='redirectToPage' href='https://enjmin.cnam.fr/enjmin/cp-spawn-2025--1535160.kjsp?RH=1499863421832'> spawn! 2025 Press Release (in French) </a>",
        jgp:"spawn! Public Day ",
        com:"<span class='text-wrapper'>General Organisation, Communication and Press<br /></span><span class='smallerText'>Stéphanie Bocquillon-Brel: stephanie.bocquillon-brel@lecnam.net<br /></span><span class='text-wrapper'><br />Partnerships<br /></span><span class='smallerText'>Indira Valdivia-Vizarreta: indira.valdivia@lecnam.net</span>",
        djp:"spawn! Professional Half-day",
        coordination:"<span class='text-wrapper'>General Organisation<br /></span><span class='smallerText'>David Elahee: david.elahee@gmail.com<br />Marie-Charlotte Ynesta: marie-charlotte@sogames.org<br /><br /></span><span class='text-wrapper'>Communication<br /></span><span class='smallerText'>Capucine Chauffourier: capucine@sogames.org</span>",
        teams:"TEAMS",
        enjminteam:"<span class='text-wrapper'>Stéphanie Bocquillon-Brel,</span><span class='smallerText'> Head of Communication<br /><br /></span><span class='text-wrapper'>Axel Buendia,</span><span class='smallerText'> School Director<br /><br /></span><span class='text-wrapper'>Eric Debenat,</span><span class='smallerText'> IT Technician<br /><br /></span><span class='text-wrapper'>Bérénice Fouchard,</span><span class='smallerText'> Graphic Designer<br /><br /></span><span class='text-wrapper'>May Hubert,</span><span class='smallerText'> Programme Assistant and Events Manager<br /><br /></span><span class='text-wrapper'>Thomas Mayoux and Florian Bonnin,</span><span class='smallerText'> Developers<br /><br /></span><span class='text-wrapper'>Linda Mikhail,</span><span class='smallerText'> Communication Officer<br /><br /></span><span class='text-wrapper'>Indira Valdivia-Vizarreta,</span><span class='smallerText'> Head of Corporate, Institutional and International Relations<br /><br /></span><span class='text-wrapper'>Margaux Virieu,</span><span class='smallerText'> General Secretary</span>",
        sogamesteam:"<span class='text-wrapper'>Capucine Chauffourier,</span><span class='smallerText'> Communication Officer<br /><br /></span><span class='text-wrapper'>Camille Coq,</span><span class='smallerText'> Selection Curator<br /><br /></span><span class='text-wrapper'>William David,</span><span class='smallerText'> Puzzle Curator<br /><br /></span><span class='text-wrapper'>David Elahee,</span><span class='smallerText'> President, Web Designer, Curation, Programme, Monitoring, Co-founder of FJA<br /><br /></span><span class='text-wrapper'>Farhanaz Elahee,</span><span class='smallerText'> Coordinator of Cap BD (an association in Angoulême which promotes the art of comic books)<br /><br /></span><span class='text-wrapper'>Sébastien Fontaine,</span><span class='smallerText'> Logistic and Co-founder of FJA,<br /><br /></span><span class='text-wrapper'>Robinson Lacotte,</span><span class='smallerText'> Experience Curator<br /><br /></span><span class='text-wrapper'>Mylène Lourdel,</span><span class='smallerText'> Event Vice-President, Programme and Curation of Conferences for the public<br /><br /></span><span class='text-wrapper'>Marie-Charlotte Ynesta,</span><span class='smallerText'> Delegate General</span>",
        guests:"Our super guests and committee members!",
        membres:"<span class='text-wrapper'>Adrien Larouzée,</span><span class='smallerText'> Head of Piloting Digital Projects - ARTE <br /></span><span class='text-wrapper'><br />⁠Céline Hirtz-Gardré,</span><span class='smallerText'> Digital Projects Officer - L'Alpha Library<br /></span><span class='text-wrapper'><br />Tanguy Taillandier,</span><span class='smallerText'> Advisor and Digital Host - CSCS/MJC Rives de Charente <br /></span>",
        membres2:"<span class='text-wrapper'>Dolly Wood,</span><span class='smallerText'> Content Creator<br /></span><span class='text-wrapper'><br />Quineapple,</span><span class='smallerText'> co-editor and Host of <i>Jour de Play</i> - ARTE<br /><br /></span><span class='text-wrapper'>David BEAUVALLET,</span><span class='smallerText'> Director of Marketing and Communication - Magelis<br /></span>",
        mentionslegales:"LEGAL NOTICE",
        enjminsiret:"<span class='titleGroup'>Cnam-Enjmin<br /><br /></span> <span class='text-wrapper-12'>Siret Number : 197 534 712 00017 - Legal status: National Public Institution of a Scientific, Cultural and Professional Nature – <br /> Activity code: </span><span class='text-wrapper-12'>Higher Education (85.42Z) – Intra-communal VAT Number : FR11197534712 - Address : 138 rue de Bordeaux 16000 Angoulême, France<br /><br /><br /></span> <span class='text-wrapper-12'>School Director: Axel Buendia<br /><br /><br /></span> <span class='titleGroup'>SO· Games<br /><br /></span> <span class='text-wrapper-12'>Siret Number: 50539681200024 – Legal status: Association loi 1901 – Activity code: Other Voluntary Associations (9499Z) <br /></span> <span class='text-wrapper-12'> Intra-communal VAT Number: FR35505396812 – Address: 12 place de la Bourse 33000 Bordeaux, France<br /><br /><br /> </span> <span class='text-wrapper-12'>President: David Elahée<br /></span>",    
        hebergement:"Website Hosting: Cnam-Enjmin. All Rights Reserved 2017-2025 – Cnam-Enjmin and SO· Games",
        fr:"French",
        en:"English",
    }
    
    window.addEventListener('load', () => {
    const selectElement = document.getElementById('modifyLang');   
    const savedValue = localStorage.getItem('langue');  
 
    if (savedValue) { 
        selectElement.value = savedValue; 
        const event = new Event('change');
        selectElement.dispatchEvent(event);
    }
});
document.getElementById('modifyLang').addEventListener('change', function() {
    console.log('La valeur a changé !');  
    localStorage.setItem('langue', this.value);
    const savedValue = localStorage.getItem('langue');
    translatePage(savedValue);
});
 
function translatePage(selectedLang) {
    if (selectedLang !== "null") {
        var elementsToModify = document.querySelectorAll('[data-change]');   
 
        elementsToModify.forEach(function(element) {
            var keyToTranslate = element.getAttribute('data-key');   
 
            if (selectedLang === "fr") {
                element.innerHTML = fr[keyToTranslate];
            }
            if (selectedLang === "en") {
                element.innerHTML = en[keyToTranslate];
            }
        });
    }
}           